name: "Tests"

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - "*"

env:
  CI: "true"

jobs:
  main:
    name: Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - ruby-version: '3.2'
            activemodel-version: '7.0'
          - ruby-version: '3.2'
            activemodel-version: '7.1'
          - ruby-version: '3.3'
            activemodel-version: '7.1'
      fail-fast: true
    env:
      ACTIVE_MODEL_VERSION: ${{ matrix.activemodel-version }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
      - run: bundle install --jobs 4 --retry 3
        name: Install Ruby deps
      - run: bundle exec rake
