name: "Tests"

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - "*"

env:
  CI: "true"

jobs:
  main:
    name: Tests
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        ruby: [3.1, 3.2, 3.3]
        activemodel: [6.1, 7.0, 7.1]
      fail-fast: true
    env:
      ACTIVE_MODEL_VERSION: ${{ matrix.activemodel }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - run: bundle install --jobs 4 --retry 3
        name: Install Ruby deps
      - run: bundle exec rake
